package product;

import com.aladin.pojo.product.Category;
import com.aladin.pojo.product.CategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_category
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKey(Category record);
}