package product;

import com.aladin.pojo.product.Picture;
import com.aladin.pojo.product.PictureExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int countByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insertSelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    List<Picture> selectByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    Picture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExample(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKeySelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_picture
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKey(Picture record);
}