package com.aladin.pojo.product;

import java.util.Date;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.detail
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.brand_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_brand.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.id
     *
     * @return the value of m_brand.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.id
     *
     * @param id the value for m_brand.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.name
     *
     * @return the value of m_brand.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.name
     *
     * @param name the value for m_brand.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.pic
     *
     * @return the value of m_brand.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.pic
     *
     * @param pic the value for m_brand.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.detail
     *
     * @return the value of m_brand.detail
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.detail
     *
     * @param detail the value for m_brand.detail
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.brand_id
     *
     * @return the value of m_brand.brand_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.brand_id
     *
     * @param brandId the value for m_brand.brand_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.c_time
     *
     * @return the value of m_brand.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.c_time
     *
     * @param cTime the value for m_brand.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.u_time
     *
     * @return the value of m_brand.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.u_time
     *
     * @param uTime the value for m_brand.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_brand.status
     *
     * @return the value of m_brand.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_brand.status
     *
     * @param status the value for m_brand.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}