package com.aladin.pojo.product;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.category_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.parent_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_category.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.id
     *
     * @return the value of m_category.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.id
     *
     * @param id the value for m_category.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.category_id
     *
     * @return the value of m_category.category_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.category_id
     *
     * @param categoryId the value for m_category.category_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.parent_id
     *
     * @return the value of m_category.parent_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.parent_id
     *
     * @param parentId the value for m_category.parent_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.name
     *
     * @return the value of m_category.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.name
     *
     * @param name the value for m_category.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.c_time
     *
     * @return the value of m_category.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.c_time
     *
     * @param cTime the value for m_category.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.u_time
     *
     * @return the value of m_category.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.u_time
     *
     * @param uTime the value for m_category.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_category.status
     *
     * @return the value of m_category.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_category.status
     *
     * @param status the value for m_category.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}