package com.aladin.pojo.product;

import java.util.Date;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.pic_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Long picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.pic1
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String pic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.pic2
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String pic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.pic3
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String pic3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.pic4
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private String pic4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_picture.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    private Date uTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.id
     *
     * @return the value of m_picture.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.id
     *
     * @param id the value for m_picture.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.pic_id
     *
     * @return the value of m_picture.pic_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.pic_id
     *
     * @param picId the value for m_picture.pic_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.pic
     *
     * @return the value of m_picture.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.pic
     *
     * @param pic the value for m_picture.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.pic1
     *
     * @return the value of m_picture.pic1
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic1() {
        return pic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.pic1
     *
     * @param pic1 the value for m_picture.pic1
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic1(String pic1) {
        this.pic1 = pic1 == null ? null : pic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.pic2
     *
     * @return the value of m_picture.pic2
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.pic2
     *
     * @param pic2 the value for m_picture.pic2
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.pic3
     *
     * @return the value of m_picture.pic3
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic3() {
        return pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.pic3
     *
     * @param pic3 the value for m_picture.pic3
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic3(String pic3) {
        this.pic3 = pic3 == null ? null : pic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.pic4
     *
     * @return the value of m_picture.pic4
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic4() {
        return pic4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.pic4
     *
     * @param pic4 the value for m_picture.pic4
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic4(String pic4) {
        this.pic4 = pic4 == null ? null : pic4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.c_time
     *
     * @return the value of m_picture.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.c_time
     *
     * @param cTime the value for m_picture.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_picture.u_time
     *
     * @return the value of m_picture.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_picture.u_time
     *
     * @param uTime the value for m_picture.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }
}