package com.aladin.pojo.product;

import java.math.BigDecimal;
import java.util.Date;

public class Specs {
    /**
     *自增id
     */
    private Long id;

    /**
     *规格单品id
     */
    private Long specsId;

    /**1
     *商品id
     */
    private Long productId;

    /**
     *单品图片资源路径
     */
    private String pic;

    /**
     *单品名称
     */
    private String name;

    /**
     *单品价格
     */
    private BigDecimal price;

    /**
     *单品规格
     */
    private String specs;

    /**
     *单品描述
     */
    private String detail;

    /**
     *库存量
     */
    private Integer stock;

    /**
     *单品状态
     */
    private Byte status;

    /**
     *单品销量
     */
    private Integer sale;

    /**
     *创建时间
     */
    private Date cTime;

    /**
     *更新时间
     */
    private Date uTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.id
     *
     * @return the value of m_specs.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.id
     *
     * @param id the value for m_specs.id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.specs_id
     *
     * @return the value of m_specs.specs_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getSpecsId() {
        return specsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.specs_id
     *
     * @param specsId the value for m_specs.specs_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setSpecsId(Long specsId) {
        this.specsId = specsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.product_id
     *
     * @return the value of m_specs.product_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.product_id
     *
     * @param productId the value for m_specs.product_id
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.pic
     *
     * @return the value of m_specs.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.pic
     *
     * @param pic the value for m_specs.pic
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.name
     *
     * @return the value of m_specs.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.name
     *
     * @param name the value for m_specs.name
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.price
     *
     * @return the value of m_specs.price
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.price
     *
     * @param price the value for m_specs.price
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.specs
     *
     * @return the value of m_specs.specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getSpecs() {
        return specs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.specs
     *
     * @param specs the value for m_specs.specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setSpecs(String specs) {
        this.specs = specs == null ? null : specs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.detail
     *
     * @return the value of m_specs.detail
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.detail
     *
     * @param detail the value for m_specs.detail
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.stock
     *
     * @return the value of m_specs.stock
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.stock
     *
     * @param stock the value for m_specs.stock
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.status
     *
     * @return the value of m_specs.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.status
     *
     * @param status the value for m_specs.status
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.sale
     *
     * @return the value of m_specs.sale
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.sale
     *
     * @param sale the value for m_specs.sale
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.c_time
     *
     * @return the value of m_specs.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.c_time
     *
     * @param cTime the value for m_specs.c_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_specs.u_time
     *
     * @return the value of m_specs.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_specs.u_time
     *
     * @param uTime the value for m_specs.u_time
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }
}