package com.aladin.pojo.dao.order;

import com.aladin.pojo.m_shopping;


public interface m_shoppingMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int insert(m_shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int insertSelective(m_shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    m_shopping selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByPrimaryKeySelective(m_shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByPrimaryKey(m_shopping record);
}