package com.aladin.dao.product;

import com.aladin.pojo.product.Brand;
import com.aladin.pojo.product.BrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    Brand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_brand
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKey(Brand record);
}