package com.aladin.dao.product;

import com.aladin.pojo.product.Specs;
import com.aladin.pojo.product.SpecsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpecsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int countByExample(SpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByExample(SpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insert(Specs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int insertSelective(Specs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    List<Specs> selectByExample(SpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    Specs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Specs record, @Param("example") SpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByExample(@Param("record") Specs record, @Param("example") SpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKeySelective(Specs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_specs
     *
     * @mbggenerated Thu Feb 14 01:20:24 CST 2019
     */
    int updateByPrimaryKey(Specs record);
}